org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false

# Token Secreto de Mapbox para descarga del SDK nativo Android (Maven Repository)
MAPBOX_DOWNLOADS_TOKEN=YOUR_MAPBOX_SECRET_TOKEN
SDK_REGISTRY_TOKEN=YOUR_MAPBOX_SECRET_TOKEN
kotlin.incremental=false
